# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: /:categories/:title

# Setup
title:            '::sp1icer'
description:      'exploit dev, red team, and random infosec thoughts.'
url:              https://sp1icer.dev
baseurl:          /

author:
  name:           'sp1icer'
  url:            https://twitter.com/sp1icer

paginate:         5

# Custom vars

github:
  repo:           https://github.com/sp1icer

plugins: [jekyll-paginate]

excerpt_separator: <!--more-->